### ISSUE TITLE
Пути images при build

### ISSUE THREAD

**Issue by evilpython** [elferno/server_webpack#1]
Приветствую. Чекнул твою сборку – очень круто.
Есть проблема, что при билде изображение генерируются с хэшем, но если вставлять их в html через img, то пути остаются без хэша. 
Ну в курсе, как можно пофиксить?
![2020-06-06_13-14-49](https://user-images.githubusercontent.com/48930627/83937561-d1fcfc80-a7f7-11ea-9f1e-25f43b50bde3.png)

**Comment by elferno** [comment]
Привет. Я только пытаюсь изучать как webpack работает, попутно изучаю GIT))
Щас попробую вставить изображение в HTML и посмотрю, что с ним происходит. Если найду решение — отпишу)

**Comment by elferno** [comment]
пофиксил … было сложно.
 
в чем собственно было проблема: когда подгружаешь, например, картинки через file-loader
{
  test: /\.(png|svg|jpg|gif)$/,
  exclude: exclude,
  loader: 'file-loader',
  options: {
    name: path.images.output
  }
},
то webpack им приписывает путь, относительно того файла, в котором эти картинки встречает, например если в CSS подключается картинка через background-image, то что делает webpack:
 
*  при перемещениее файла картинки - смотрит  path . images . output (./assets/images/[name].[hash].[ext]) — ага, значит кладу картинку в production/assets/images/...
*  при переписывании URL в background-image - смотрит  path . images . output (./assets/images/[name].[hash].[ext]) — ага, значит  background-image: URL( ./assets/images/... ) — НО! сам-то css файл лежит в  ./assets/css/ и получается, что путь к картинке на выходе в браузер будет:  background-image: URL( ./assets/css/assets/images/... )
понимаешь какая подстава? Чтобы это пофиксить хоть как-то, я приписал publickPath
 
{
  test: /\.(png|svg|jpg|gif)$/,
  exclude: exclude,
  loader: 'file-loader',
  options: {
    publicPath: '../../',
    name: path.images.output
  }
},
логично же? пусть теперь стает: background-image: URL(../../ ./assets/css/assets/images/... ) — что попадает ровно куда нам надо и все работает.
 
Теперь, чтобы подключить картинку в HTML напрямую, нам надо установить mpn i -D lodash и вставлять картинку как: 
<img src="<%=require('./assets/images/logo.png')%>" alt="">
Тогда webpack перепишет ей путь при сборке и все должно быть нормально но … вспоминаем решение с publickPath: ‘../../’ и, если в случае с CSS оно помогает, то здесь, относительно файла index.html получается путь:
<img src="../.././assets/images/..." alt="">
который ведет за корень сайта)) В итоге либо картинка из HTML не будет работать, либо картинки из CSS, который в папке /assets/css/
 
вообщем посомтри как я решил эту дичь (запушил на гит обновление)

**Comment by evilpython** [comment]
Да, такой импорт картинок работает. Теперь нужно найти решение правильности путей после билда.

**Comment by elferno** [comment]
Так оно уже найдено. Все в переменной path.host

**Comment by evilpython** [comment]
Не, всё круто, оно работает, но по факту при билде он прописывает в путях `http://localhost:63342/server_webpack/production/...`
и приходится вручную прописывать в html и css относительные пути.

Ну или я что-то не так делаю...

**Comment by elferno** [comment]
Так суть самой проблемы и решается только прописыванием АБСОЛЮТНОГО пути для html-картинок и css-картинок. Потому что, как я обяснял ранее — webpack путь до картинок строит не осмысленно, а по заданному шаблону:
{
  test: /\.(png|svg|jpg|gif)$/,
  exclude: exclude,
  loader: 'file-loader',
  options: {
    esModule: false,
    path: path.root,
    publicPath: path.host,
    name: path.images.output
  }
},
path.images.output = `assets/images/[name].[hash].[ext]`
на основе  options.name  поэтому, если НЕ указать publickPath - в css путь до картинки будет создан как:
 
/assets/css/ (путь до самого файла css) + /assets/images/ (путь из переменной  path . images . output ) = /assets/css/assets/images/… 
 
publickPath — это удет приделано ПЕРЕД  path . images . output для ВСЕХ img-файлов, т.е. для CSS можно было бы задать publickPath  = ‘../../’ и webpack бы делал:
 
/assets/css/ (путь до самого файла css) + ‘../../’ (publickPath ) + /assets/images/ (путь из переменной  path . images . output ) = /assets/css/../../assets/images/… — тут, кусок «/assets/css/../../» — приводит нас в корень сайта и далее идет в «/assets/images/…» — где и лежат картинки…. все работает, но
 
но… для html, webpack проделает то же самое с путями картинок, а поскольку html УЖЕ лежит в КОРНЕ сайта — финальный путь получится неправильным
 
Из этого я придумал только 1 решение — абсолютный путь для картинок, вместо относительного. Если найдешь какой-то другой вариант, который позволяет сохранять относительные пути — пожалуйста напиши, мне интересно как это делать

**Comment by elferno** [comment]
когда ты на рельный рабочий сервер выложишь сайт, ты в переменную:
const server = devMode ? 'http://localhost:8000/' : 'http://localhost:63342/server_webpack/production/'
впишешь свой хост:
 
const server = 'https://yoursite.com/'
 
и адреса будут:  https://yoursite.com/img/...
